#General Settings
LANGUAGE=EN

DEFAULT_EXPIRY_DAYS=180

localDatastoreFormat=firebird

#Directory Settings
IMPORT_DIR=%REGION_HOME%/Import
EXPORT_DIR=%REGION_HOME%/Export
MAPLAYERS_DIR=%REGION_HOME%/MapsCache
DUMP_DIR=%REGION_HOME%/DumpFiles

#Executable Directories
PYTHON_EXE=%REGION_HOME%/Modules/Python39/Scripts/python.exe
