#%%
import matplotlib.pyplot as plt
import geopandas as gpd
import numpy as np
import os

# Load the updated shapefile with statistics
gdf1 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim1.shp")
gdf2 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim2.shp")
gdf3 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim3.shp")
gdf4 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim4.shp")
gdf5 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim5.shp")
gdf6 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim6.shp")
gdf7 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim7.shp")
gdf8 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim8.shp")
gdf9 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim9.shp")
gdf10 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim10.shp")
gdf11 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim11.shp")
gdf12 = gpd.read_file("./journal/shapefiles/selected_Journal_Sim12.shp")

savedir = './journal/plots/'
os.makedirs(savedir, exist_ok=True)

def add_to_plot(ax, gdf, plot_field, marker_style, line_color, label_text):
    gdf_sorted = gdf.sort_values(by=plot_field).dropna(subset=plot_field)
    ax.plot(gdf_sorted[plot_field].values, np.linspace(0,1,len(gdf_sorted)), marker_style, color=line_color, label=label_text)
    return ax

# CDF plot Spearman correlation for Nodes using only good values
fig, ax = plt.subplots(figsize=(8, 8))
add_to_plot(ax, gdf1, 'sp_N', '-', 'black', 'all data - 1 Node')
add_to_plot(ax, gdf7, 'sp_N', '--', 'black', 'all data - 3 Nodes')
add_to_plot(ax, gdf4, 'sp_N', '-', 'gray', 'no ice-covered - 1 Node')
add_to_plot(ax, gdf10, 'sp_N', '--', 'gray', 'no ice-covered - 3 Nodes')
ax.set_xlabel('Spearman correlation coefficient [-]')
ax.set_ylabel('Cumulative Distribution Function (CDF)')
ax.set_title('CDF of Spearman correlation for Nodes using only good values')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'cdf_spearman_Nodes_good.png')
plt.close()

# CDF plot Spearman correlation for Nodes using suspect values and better
fig, ax = plt.subplots(figsize=(8, 8))
add_to_plot(ax, gdf2, 'sp_N', '-', 'black', 'all data - 1 Node')
add_to_plot(ax, gdf8, 'sp_N', '--', 'black', 'all data - 3 Nodes')
add_to_plot(ax, gdf5, 'sp_N', '-', 'gray', 'no ice-covered - 1 Node')
add_to_plot(ax, gdf11, 'sp_N', '--', 'gray', 'no ice-covered - 3 Nodes')
ax.set_xlabel('Spearman correlation coefficient [-]')
ax.set_ylabel('Cumulative Distribution Function (CDF)')
ax.set_title('CDF of Spearman correlation for Nodes using suspect values and better')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'cdf_spearman_Nodes_suspect.png')
plt.close()

# CDF plots Spearman correlation for Nodes using degraded values
fig, ax = plt.subplots(figsize=(8, 8))
add_to_plot(ax, gdf3, 'sp_N', '-', 'black', 'all data - 1 Node')
add_to_plot(ax, gdf9, 'sp_N', '--', 'black', 'all data - 3 Nodes')
add_to_plot(ax, gdf6, 'sp_N', '-', 'gray', 'no ice-covered - 1 Node')
add_to_plot(ax, gdf12, 'sp_N', '--', 'gray', 'no ice-covered - 3 Nodes')
ax.set_xlabel('Spearman correlation coefficient [-]')
ax.set_ylabel('Cumulative Distribution Function (CDF)')
ax.set_title('CDF of Spearman correlation for Nodes using degraded values and better')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'cdf_spearman_Nodes_degrade.png')
plt.close()

'''
# CDF plots BIAS for Nodes using suspect values
fig, ax = plt.subplots(figsize=(8, 8))
add_to_plot(ax, gdf2, 'b_N', '-r', 'includes ice for 1 Node')
add_to_plot(ax, gdf8, 'b_N', '-b', 'includes ice for 3 Nodes')
add_to_plot(ax, gdf5, 'b_N', '--r', 'excludes ice for 1 Node')
add_to_plot(ax, gdf11, 'b_N', '--b', 'excludes ice for 3 Nodes')
ax.set_xlabel('BIAS [m]')
ax.set_ylabel('Cumulative Distribution Function (CDF)')
ax.set_title('CDF of BIAS for Nodes using suspect values')
ax.grid(True)
ax.legend()
ax.set_xscale('log')
fig.tight_layout()
plt.savefig(savedir + 'cdf_bias_Nodes_suspect.png')
plt.close()

# Bar plot for number of good values for Nodes filtering for suspect values
fig, ax = plt.subplots(figsize=(8, 8))
ax.bar(gdf2['STATION_NU'], gdf2['good_N'], color='red', label='Using 1 Node')
ax.bar(gdf8['STATION_NU'], gdf8['good_N'], color='blue', label='Using 3 Nodes')
ax.set_xlabel('Stations')
ax.set_ylabel('Number of good points')
ax.set_title('Number of good values for Nodes filtering for suspect values')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'bar_points_Nodes_suspect.png')
plt.close()

# RMSE CDF plots
fig, ax = plt.subplots(figsize=(8, 8))
add_to_plot(ax, gdf2, 'rmse_N', '-r', 'includes ice for 1 Node')
add_to_plot(ax, gdf8, 'rmse_N', '-b', 'includes ice for 3 Nodes')
add_to_plot(ax, gdf5, 'rmse_N', '--r', 'excludes ice for 1 Node')
add_to_plot(ax, gdf11, 'rmse_N', '--b', 'excludes ice for 3 Nodes')
ax.set_xlabel('RMSE')
ax.set_ylabel('Cumulative Distribution Function (CDF)')
ax.set_title('CDF of RMSE for SWOT Node and Reach')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'cdf_rmse_both.png')
plt.close()

gdf_sorted_node = gdf.sort_values(by='r_N').dropna()
gdf_noIce_sorted_node = gdf_noIce.sort_values(by='r_N').dropna()
gdf_sorted_reach = gdf.sort_values(by='r_R').dropna()
gdf_noIce_sorted_reach = gdf_noIce.sort_values(by='r_R').dropna()
ax.plot(gdf_sorted_node['r_N'].values, np.linspace(0,1,len(gdf_sorted_node)), label='SWOT Node', color='red')
ax.plot(gdf_sorted_reach['r_R'].values, np.linspace(0,1,len(gdf_sorted_reach)), label='SWOT Reach', color='blue')
ax.plot(gdf_noIce_sorted_node['r_N'].values, np.linspace(0,1,len(gdf_noIce_sorted_node)), label='SWOT Node (No Ice)', color='red', linestyle='dashed')
ax.plot(gdf_noIce_sorted_reach['r_R'].values, np.linspace(0,1,len(gdf_noIce_sorted_reach)), label='SWOT Reach (No Ice)', color='blue', linestyle='dashed')

# CDF plots for r
fig, ax = plt.subplots(figsize=(8, 8))
gdf_sorted_node = gdf.sort_values(by='sp_N').dropna()
gdf_noIce_sorted_node = gdf_noIce.sort_values(by='sp_N').dropna()
gdf_sorted_reach = gdf.sort_values(by='sp_R').dropna()
gdf_noIce_sorted_reach = gdf_noIce.sort_values(by='sp_R').dropna()
ax.plot(gdf_sorted_node['sp_N'].values, np.linspace(0,1,len(gdf_sorted_node)), label='SWOT Node', color='red')
ax.plot(gdf_sorted_reach['sp_R'].values, np.linspace(0,1,len(gdf_sorted_reach)), label='SWOT Reach', color='blue')
ax.plot(gdf_noIce_sorted_node['sp_N'].values, np.linspace(0,1,len(gdf_noIce_sorted_node)), label='SWOT Node (No Ice)', color='red', linestyle='dashed')
ax.plot(gdf_noIce_sorted_reach['sp_R'].values, np.linspace(0,1,len(gdf_noIce_sorted_reach)), label='SWOT Reach (No Ice)', color='blue', linestyle='dashed')
ax.set_xlabel('Spearman correlation coefficient')
ax.set_ylabel('Cumulative Distribution Function (CDF)')
ax.set_title('CDF of Spearman correlation coefficient for SWOT Node and Reach')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'cdf_spearman_r_both.png')
plt.close()

# BIAS CDF plots
fig, ax = plt.subplots(figsize=(8, 8))
gdf_sorted_node = gdf.sort_values(by='b_N').dropna()
gdf_sorted_reach = gdf.sort_values(by='b_R').dropna()
gdf_noIce_sorted_node = gdf_noIce.sort_values(by='b_N').dropna()
gdf_noIce_sorted_reach = gdf_noIce.sort_values(by='b_R').dropna()
ax.plot(gdf_sorted_node['b_N'].values, np.linspace(0,1,len(gdf_sorted_node)), label='SWOT Node', color='red')
ax.plot(gdf_sorted_reach['b_R'].values, np.linspace(0,1,len(gdf_sorted_reach)), label='SWOT Reach', color='blue')
ax.plot(gdf_noIce_sorted_node['b_N'].values, np.linspace(0,1,len(gdf_noIce_sorted_node)), label='SWOT Node (No Ice)', color='red', linestyle='dashed')
ax.plot(gdf_noIce_sorted_reach['b_R'].values, np.linspace(0,1,len(gdf_noIce_sorted_reach)), label='SWOT Reach (No Ice)', color='blue', linestyle='dashed')
ax.set_xlabel('BIAS')
ax.set_ylabel('Cumulative Distribution Function (CDF)')
ax.set_title('CDF of BIAS for SWOT Node and Reach')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'cdf_bias_both.png')
plt.close()

# Correlation vs width
fig, ax = plt.subplots(figsize=(8, 8))
gdf_sorted_node = gdf.sort_values(by='width').dropna()
gdf_sorted_reach = gdf.sort_values(by='width').dropna()
gdf_noIce_sorted_node = gdf_noIce.sort_values(by='width').dropna()
gdf_noIce_sorted_reach = gdf_noIce.sort_values(by='width').dropna()
ax.scatter(gdf_sorted_node['width'].values, gdf_sorted_node['r_N'].values, label='SWOT Node', facecolor='none', marker='o', s=10, edgecolor='red')
ax.scatter(gdf_sorted_reach['width'].values, gdf_sorted_reach['r_R'].values, label='SWOT Reach', facecolor='none', marker= 'o', s=10, edgecolor='blue')
ax.scatter(gdf_noIce_sorted_node['width'].values, gdf_noIce_sorted_node['r_N'].values, label='SWOT Node (No Ice)', facecolor='none', marker='o', s=10, edgecolor='green')
ax.scatter(gdf_noIce_sorted_reach['width'].values, gdf_noIce_sorted_reach['r_R'].values, label='SWOT Reach (No Ice)', facecolor='none', marker= 'o', s=10, edgecolor='orange')
ax.set_xlabel('Width')
ax.set_ylabel('Pearson correlation coefficient (r)')
ax.set_title('Relation between Width and Pearson correlation coefficient (r) for SWOT Node and Reach')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'relation_width_pearson_r_both.png')
plt.close()

# Correlation vs number of data points
fig, ax = plt.subplots(figsize=(8, 8))
gdf_sorted_node = gdf.sort_values(by='width').dropna()
gdf_sorted_reach = gdf.sort_values(by='width').dropna()
gdf_noIce_sorted_node = gdf_noIce.sort_values(by='width').dropna()
gdf_noIce_sorted_reach = gdf_noIce.sort_values(by='width').dropna()
ax.scatter(gdf_sorted_node['data_N'].values, gdf_sorted_node['r_N'].values, label='SWOT Node', facecolor='none', marker='o', s=10, edgecolor='red')
ax.scatter(gdf_sorted_reach['data_R'].values, gdf_sorted_reach['r_R'].values, label='SWOT Reach', facecolor='none', marker= 'o', s=10, edgecolor='blue')
ax.scatter(gdf_noIce_sorted_node['data_N'].values, gdf_noIce_sorted_node['r_N'].values, label='SWOT Node (No Ice)', facecolor='none', marker='o', s=10, edgecolor='green')
ax.scatter(gdf_noIce_sorted_reach['data_R'].values, gdf_noIce_sorted_reach['r_R'].values, label='SWOT Reach (No Ice)', facecolor='none', marker= 'o', s=10, edgecolor='orange')
ax.set_xlabel('Number of data points')
ax.set_ylabel('Correlation coefficient (r)')
ax.set_title('Relation between Number of Data Points and Correlation coefficient (r) for SWOT Node and Reach')
ax.grid(True)
ax.legend()
fig.tight_layout()
plt.savefig(savedir + 'relation_data_points_both.png')
plt.close()
'''
